### ISSUE TITLE
@Testcontainers annotation not required

### ISSUE THREAD

**Issue by kiview** [RadarCOVID/radar-covid-backend-verification-server#2]
Hi, I am the author of the `testcontainers-spock` extension and a `testcontainers-java` maintainer. I was very happy to see, that you are using Testcontainers for your testing needs.

However, the way I see your use case, you don't even need to include the `@Testcontainers` annotation (as you do here https://github.com/RadarCOVID/radar-covid-backend-verification-server/blob/master/verification-server-boot/src/test/groovy/es/gob/radarcovid/verification/persistence/test/CCAADaoTestSpec.groovy#L21), since you are relying on the Testcontainers JDBC driver. This works already without the annotation.

In case you have any further questions or problems, I'd be glad to help and support your efforts.

**Comment by iCesofT** [comment]
Hi Kevin,

thanks for your comment. We will take out the import.

Kind regards
