### ISSUE TITLE
Possible security breach because no random data are sent.

### ISSUE THREAD

**Issue by ouboub** [RadarCOVID/radar-covid-backend-verification-server#6]
Hi

I just learned about this: 
https://elpais.com/tecnologia/2020-10-22/la-app-radar-covid-ha-tenido-una-brecha-de-seguridad-desde-su-lanzamiento.html

is this true? Does it apply to the iOS and the Android version?
What are the plans to resolve it.

thanks

Uwe Brauer

**Comment by iCesofT** [comment]
Solved on https://github.com/RadarCOVID/radar-covid-backend-verification-server/blob/develop/CHANGELOG.md#103release---2020-10-09

**Comment by ouboub** [comment]
So what is the state of art, fixed or not?
If fixed, is this already in the newest release.

**Comment by ouboub** [comment]
Hi
I hate to be a PITA, but there was no comment! 
The issue was closed and then reopened.
@iCesofT  could you please clarify the state of art?
thanks

**Comment by pantic79** [comment]
See [this](https://github.com/RadarCOVID/radar-covid-ios/issues/36). We will keep this issue opened until the vulnerability public disclosure is performed.

Thanks.

**Comment by ouboub** [comment]
> See [this](https://github.com/RadarCOVID/radar-covid-ios/issues/36). We will keep this issue opened until the vulnerability public disclosure is performed.
> 
> Thanks.

is it commit 1d8b145b7e40534c9a135a5515284e3739678473
which is supposed to solve this issue?

**Comment by pantic79** [comment]
No, you are looking into the wrong side. In fact, the backend server was ready to process fake positives with some minor adjustments. You should look into the APPs side starting to send false positives to server. For example (not exhaustive): RadarCOVID/radar-covid-android@7e1ecc011b47f174894af9c3bdbf81cca37008d6, RadarCOVID/radar-covid-ios@2c7f498bb22b8ad479ec1b401b098f9054474211.

Thanks.

**Comment by ouboub** [comment]
> No, you are looking into the wrong side. In fact, the backend server was ready to process fake positives with some minor adjustments. You should look into the APPs side starting to send false positives to server. For example (not exhaustive): [RadarCOVID/radar-covid-android@7e1ecc0](https://github.com/RadarCOVID/radar-covid-android/commit/7e1ecc011b47f174894af9c3bdbf81cca37008d6), [RadarCOVID/radar-covid-ios@2c7f498](https://github.com/RadarCOVID/radar-covid-ios/commit/2c7f498bb22b8ad479ec1b401b098f9054474211).
> 
> Thanks.

I see, thanks for the information

**Comment by iCesofT** [comment]
We close the issue as long as apps are sending fake positives and backend processing them.

**Comment by pantic79** [comment]
See https://github.com/RadarCOVID/radar-covid-backend-dp3t-server/security/advisories/GHSA-w7jx-37x3-w2jx
