### ISSUE TITLE
Build failure on CentOS 7

### ISSUE THREAD

**Issue by gatemezing** [RadarCOVID/radar-covid-backend-verification-server#7]
Hello,
I've been trying to follow the installation guide for Docken Environment on Centos 7. 
I use this command `mvn clean package -P docker-env` but I have errors during the building. Any hints? Thanks again for this great work. 
See below my console output 

[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-banned-dependencies) @ verification-server-parent ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] es.gob.radarcovid:verification-server-parent ...... FAILURE [0.975s]
[INFO] es.gob.radarcovid:verification-server-api ......... SKIPPED
[INFO] es.gob.radarcovid:verification-server-service ..... SKIPPED
[INFO] es.gob.radarcovid:verification-server-boot ........ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.574s
[INFO] Finished at: Sun Nov 01 19:03:17 UTC 2020
[INFO] Final Memory: 14M/54M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-banned-dependencies) on project verification-server-parent: A type incompatibility occured while executing org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce: class org.sonatype.aether.util.DefaultRepositorySystemSession cannot be cast to class org.eclipse.aether.RepositorySystemSession (org.sonatype.aether.util.DefaultRepositorySystemSession is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4a574795; org.eclipse.aether.RepositorySystemSession is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @867ba60)
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/centos/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M3/maven-enforcer-plugin-3.0.0-M3.jar
[ERROR] urls[1] = file:/home/centos/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[2] = file:/home/centos/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[3] = file:/home/centos/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[4] = file:/home/centos/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[5] = file:/home/centos/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar
[ERROR] urls[6] = file:/home/centos/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[7] = file:/home/centos/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[8] = file:/home/centos/.m2/repository/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar
[ERROR] urls[9] = file:/home/centos/.m2/repository/org/apache/maven/enforcer/enforcer-api/3.0.0-M3/enforcer-api-3.0.0-M3.jar
[ERROR] urls[10] = file:/home/centos/.m2/repository/junit/junit/4.11/junit-4.11.jar
[ERROR] urls[11] = file:/home/centos/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] urls[12] = file:/home/centos/.m2/repository/org/apache/maven/enforcer/enforcer-rules/3.0.0-M3/enforcer-rules-3.0.0-M3.jar
[ERROR] urls[13] = file:/home/centos/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.1.0/maven-common-artifact-filters-3.1.0.jar
[ERROR] urls[14] = file:/home/centos/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.jar
[ERROR] urls[15] = file:/home/centos/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[16] = file:/home/centos/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
[ERROR] urls[17] = file:/home/centos/.m2/repository/commons-codec/commons-codec/1.12/commons-codec-1.12.jar
[ERROR] urls[18] = file:/home/centos/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar
[ERROR] urls[19] = file:/home/centos/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.jar
[ERROR] urls[20] = file:/home/centos/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.4.1/maven-resolver-util-1.4.1.jar
[ERROR] urls[21] = file:/home/centos/.m2/repository/org/apache/maven/resolver/maven-resolver-api/1.4.1/maven-resolver-api-1.4.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by iCesofT** [comment]
Hi,

could you please let us know JDK version & Maven version? I know that it's not the same but I tried with a Centos 7 Docker image, installing [SdkMan](https://sdkman.io/) and then:

```shell
$ sdk install java 11.0.9.hs-adpt
$ sdk install maven 3.6.3
```

And I was able to compile (without test because I'm inside a Docker container and Testcontainers don't run inside a container):

```shell
[INFO] --- spring-boot-maven-plugin:2.3.4.RELEASE:repackage (repackage) @ verification-server-boot ---
[INFO] Attaching repackaged archive /scm/radar-covid-backend-verification-server/verification-server-boot/target/docker/verification-server-boot-1.1.1-SNAPSHOT-exec.jar with classifier exec
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for es.gob.radarcovid:verification-server-parent 1.1.1-SNAPSHOT:
[INFO]
[INFO] es.gob.radarcovid:verification-server-parent ....... SUCCESS [  2.443 s]
[INFO] es.gob.radarcovid:verification-server-api .......... SUCCESS [  4.447 s]
[INFO] es.gob.radarcovid:verification-server-service ...... SUCCESS [  7.675 s]
[INFO] es.gob.radarcovid:verification-server-boot ......... SUCCESS [  7.150 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.669 s
[INFO] Finished at: 2020-11-02T22:43:31Z
[INFO] ------------------------------------------------------------------------
[root@15b4b869a070 radar-covid-backend-verification-server]#
```

**Comment by gatemezing** [comment]
Hola @iCesofT , 
Thanks for your feedback. I have installed in my ENV JDK 11.0.8 and  Maven 3.0.5 I put the screenshot below. HTH
<img width="617" alt="Capture d’écran 2020-11-03 à 09 57 11" src="https://user-images.githubusercontent.com/922883/97965943-6a090d00-1dbb-11eb-9f94-c51af800c43c.png">

**Comment by iCesofT** [comment]
That's the issue.. You installed Maven 3.0.. Requirements are 3.6 as you can see on pom.xml file:
https://github.com/RadarCOVID/radar-covid-backend-verification-server/blob/3014e7563ebc8f58808cbb20b65335d9007d190c/pom.xml#L30
https://github.com/RadarCOVID/radar-covid-backend-verification-server/blob/3014e7563ebc8f58808cbb20b65335d9007d190c/pom.xml#L488

Thank you for this issue, we will review the README.md file and add the comment to Maven version 3.6.

**Comment by gatemezing** [comment]
Yeah, you are right. Thanks! SOLVED! I close this and open other issue related to running the project.
