### ISSUE TITLE
Running the project failure on CentOS 7

### ISSUE THREAD

**Issue by gatemezing** [RadarCOVID/radar-covid-backend-verification-server#8]
Hi @iCesofT 
I've successfully built the project and wanted to run it (thanks for the Maven version tip). I follow the commands: `docker-compose up -d postgres` (OK). However, I have an error with the second command `docker-compose up -d backend`.  (see screenshot). Anything that I'm doing wrong? TIA
<img width="748" alt="Capture d’écran 2020-11-03 à 13 32 51" src="https://user-images.githubusercontent.com/922883/97986399-edd1f200-1dd9-11eb-9540-edd5d8de361b.png">

**Comment by iCesofT** [comment]
Hi @gatemezing.

Please update your repository as long as we upgraded to 1.1.0.RELEASE (in master branch) or 1.1.1-SNAPSHOT (on develop branch) five days ago.

You don't need to run `docker-compose` from the target folder (`verification-server-boot/target`), please, run it on the parent folder (where you can find the `docker-compose.yml` file).

I compiled right now and both services (postgres and backend) are up and running:

```shell
❯ docker-compose ps
                       Name                                     Command               State           Ports
--------------------------------------------------------------------------------------------------------------------
radar-covid-backend-verification-server_backend_1    sh -c java $JAVA_OPTS -Dja ...   Up      0.0.0.0:8080->8080/tcp
radar-covid-backend-verification-server_postgres_1   docker-entrypoint.sh postgres    Up      0.0.0.0:5432->5432/tcp
```

**Comment by gatemezing** [comment]
I did a new `git clone <repo>`. Then I tried to build again, with the cmd `mvn clean package -P docker-env` but now I get a new build failure. Not sure actually what I'm doing wrong here. (see capture)
<img width="867" alt="Capture d’écran 2020-11-03 à 16 56 00" src="https://user-images.githubusercontent.com/922883/98012903-eae6f980-1df9-11eb-9542-e5f268b1fe76.png">

Also, regarding the original error running Docker, I had the same error even running the command from the parent folder (that was before I update the repo). Thanks for your time.

**Comment by iCesofT** [comment]
Hi @gatemezing, could you please show / put the log info? It's quite strange since I already compiled again downloading the latest develop branch.

**Comment by gatemezing** [comment]
Hi @iCesofT , sorry for the delay.
I came back to the issue today and found that I was able to build without any issue. 
Regarding the docker-compose, I had a small issue with the error [here](https://github.com/docker/compose/issues/4950) that I was able to solve. So, everything fine today. Thanks for your help. 
<img width="823" alt="Capture d’écran 2020-11-07 à 14 53 30" src="https://user-images.githubusercontent.com/922883/98443082-60f4a480-2109-11eb-8d9a-5a38f33381c9.png">
